### PR TITLE
Updates for PSA Crypto API 1.0b3

### PR DESCRIPTION
**Pull request by Patater**
Also, add a "Getting Started" example, using all the examples from our getting started guide (matching the code in https://github.com/ARMmbed/mbed-crypto/pull/232).

### CODE REVIEW

**Review by yanesca — APPROVED** [review]
Looks good to me.

**Review by dgreen-arm — APPROVED** [review]
Looks good to me

**Review by dgreen-arm — CHANGES_REQUESTED** [review]
Actually it would be good to have a target log, like the other examples do, so we can test that its up to date and working correctly.

Adding a `getting-started.log` with 
```
-- Begin Mbed Crypto Getting Started --

Import an AES key...\tImported a key
Sign a message...\tSigned a message
Encrypt with cipher...\tEncrypted plaintext
Decrypt with cipher...\tDecrypted ciphertext
Hash a message...\tHashed a message
Verify a hash...\tVerified a hash
Generate random...\tGenerated random data
Derive a key (HKDF)...\tDerived key
Authenticate encrypt...\tAuthenticated and encrypted
Authenticate decrypt...\tAuthenticated and decrypted
Generate a key pair...\tExported a public key

-- End Mbed Crypto Getting Started --
```
should do the trick

**Comment by Patater** [comment]
> Actually it would be good to have a target log, like the other examples do, so we can test that its up to date and working correctly.

Gah, somebody put `*.log` in the gitignore, so this PR didn't include my log...

**Comment by Patater** [comment]
> > Actually it would be good to have a target log, like the other examples do, so we can test that its up to date and working correctly.
> 
> Gah, somebody put `*.log` in the gitignore, so this PR didn't include my log...

Gah, it was me and my .gitignore_global file.

**Comment by Patater** [comment]
Rebased to add log in the example adding commit

**Comment by Patater** [comment]
Rebased to turn `\t` into real tabs

**Comment by Patater** [comment]
Testing done:

```
$ mbedhtrun -m K64F -P 600 --sync=0 -v --compare-log ../tests/getting-started.log -f BUILD/K64F/GCC_ARM/getting-started.bin -d /media/DAPLINK/ -p /dev/ttyACM0
HOST: Inspecting './test/host_tests' for local host tests...
[1566987267.98][HTST][INF] host test executor ver. 0.0.8
[1566987267.98][HTST][INF] copy image onto target...
[1566987280.51][MBED][WRN] Target ID not found: Skipping flash check and retry
[1566987280.52][HTST][INF] starting host test process...
[1566987280.53][CONN][INF] starting connection process...
[1566987280.53][CONN][INF] notify event queue about extra 600 sec timeout for serial port pooling
[1566987280.53][CONN][INF] initializing serial port listener... 
[1566987280.53][SERI][INF] serial(port=/dev/ttyACM0, baudrate=9600, read_timeout=0.01, write_timeout=5)
[1566987280.53][HTST][INF] setting timeout to: 600 sec
[1566987280.53][SERI][INF] reset device using 'default' plugin...
[1566987280.64][SERI][INF] waiting 1.00 sec after reset
[1566987281.64][SERI][INF] wait for it...
[1566987281.64][SERI][TXD] mbedmbedmbedmbedmbedmbedmbedmbedmbedmbed
[1566987281.64][CONN][WRN] skipping __sync packet (specified with --sync=0)
[1566987281.65][CONN][RXD] -- Begin Mbed Crypto Getting Started --
[1566987281.65][CONN][RXD] 
[1566987281.65][CONN][RXD] Import an AES key...	Imported a key
[1566987281.65][CONN][RXD] Sign a message...	Signed a message
[1566987281.65][CONN][RXD] Encrypt with cipher...	Encrypted plaintext
[1566987281.66][CONN][RXD] Decrypt with cipher...	Decrypted ciphertext
[1566987281.66][CONN][RXD] Hash a message...	Hashed a message
[1566987281.66][CONN][RXD] Verify a hash...	Verified a hash
[1566987281.66][CONN][RXD] Generate random...	Generated random data
[1566987281.66][CONN][RXD] Derive a key (HKDF)...	Derived key
[1566987281.66][CONN][RXD] Authenticate encrypt...	Authenticated and encrypted
[1566987281.66][CONN][RXD] Authenticate decrypt...	Authenticated and decrypted
[1566987281.89][CONN][RXD] Generate a key pair...	Exported a public key
[1566987281.89][CONN][RXD] 
[1566987281.94][CONN][RXD] -- End Mbed Crypto Getting Started --
[1566987281.94][HTST][INF] Target log matches compare log!
[1566987281.94][HTST][INF] test suite run finished after 1.41 sec...
[1566987281.95][CONN][INF] received special event '__host_test_finished' value='True', finishing
[1566987281.95][HTST][INF] CONN exited with code: 0
[1566987281.95][HTST][INF] No events in queue
[1566987281.95][HTST][INF] stopped consuming events
[1566987281.95][HTST][INF] host test result() call skipped, received: True
[1566987281.95][HTST][WRN] missing __exit event from DUT
[1566987281.95][HTST][WRN] missing __exit_event_queue event from host test
[1566987281.95][HTST][INF] calling blocking teardown()
[1566987281.95][HTST][INF] teardown() finished
[1566987281.95][HTST][INF] {{result;success}}
```

**Review by dgreen-arm — APPROVED** [review]

**Pull request merged**
